#!/bin/bash

shopt -s extglob

LO=${LO-200} HI=${HI-250}

dispatch () { :; }
[[ -e .config ]] && source ./.config
[[ -e dispatch.bash ]] && source ./dispatch.bash

diemsg=
die () { diemsg=$*; exit 1; }

resetterm () {
    local escapes=(
        '\e[m'      # sgr state
        '\e[?25h'   # show cursor
        '\e8'       # restore cursor pos
        '\e[?1049l' # alt screen off
        '\e[?1000l' # mouse mode
        '\e[?1006l' # sgr mouse mode idk whatever
        '\e[?1002l' # mouse button even tracking
        '\e[?1016l' # mouse returns pixels
        '\e8'       # restore cursor pos
    )
    printf %b "${escapes[@]}"
    stty sane
}
exitfunc () {
    resetterm
    [[ $diemsg ]] && echo "$diemsg"
    balltimes
    dispatch exit
}

balltimes () {
    sorted=() sum=0 counted=()
    ((${#balltimes[@]})) || return
    for n in "${balltimes[@]}"; do
        ((sum += n))
        ((counted[n]++))
    done
    for n in "${!counted[@]}"; do
        for ((i=0; i<counted[n]; i++)) do
            sorted+=("$n")
        done
    done

    min=${sorted[0]} max=${sorted[-1]}
    ballcount=${#sorted[@]}
    mean=$((sum/ballcount))
    sum=0 sqdiffs=()
    for i in "${!sorted[@]}"; do
        ((sum+=(sqdiffs[i]=(sorted[i]-mean)**2)))
    done
    variance=$((sum/ballcount))

    # newton's method
    x=$((variance/2))
    while ((x)); do
        ((prev=x,x=(x+variance/x)/2,x==prev)) && break
    done
    stddev=$x

    echo 'metaball count' "$ballcount"
    printf "fastest metaball %'dµs\n" "$min"
    printf "slowest metaball %'dµs\n" "$max"
    printf "average metaball %'dµs\n" "$mean"
    printf "95th %%ile %'dµs\n" "${sorted[ballcount*95/100]}"
    printf "std dev %'dµs\n" "$stddev"
    echo 'sizes' "colw=$colw rowh=$rowh winh=$winh winw=$winw"
}


trap exitfunc exit

[[ $ALREADY_REEXECD ]] && {
    notify=($NOTIFY)
    dispatch=($DISPATCH)
} || {
    export ALREADY_REEXECD=1
    export NOTIFY=${notify[*]}
    export DISPATCH=${dispatch[*]}
    stty raw -echo
    # exec "$BASH" "$0"
    # todo
}

escapes=(
    '\e[?1049h'  # alt screen
    '\e[J'       # erase screen
    '\e[?25l'    # hide cursor
    '\e7'        # save cursor pos
    '\e[?1000h'  # mouse mode
    '\e[?1002h'  # mouse button even tracking
    '\e[?1006h'  # sgr mouse mode idk whatever
    '\e[?1016h'  # mouse returns pixels
    '\e[?1000$p' # query mouse mode
    '\e[?1002$p' # query mouse button even tracking
    '\e[?1006$p' # query sgr mouse mode idk whatever
    '\e[?1016$p' # query mouse returns pixels
    '\e[14t'     # window size in pixels
    '\e[16t'     # cell size in pixels
    '\e[18t'     # term size in cells
    '\e[?6n'     # cursor position just to definitely get a reply
)

initterm () {
    local REPLY
    while read -rn1 -t.01; [[ $REPLY ]]; do :; done

    printf %b "${escapes[@]}"
    read -r -t.1 -d R
    csi=$'\e\['
    qregex=';([^$]+)[$]y' # decrqm replies
    tregex=';([^;]+);([^t]+)t'

    regex=
    regex+="(${csi}[?]1000$qregex)?"
    regex+="(${csi}[?]1002$qregex)?"
    regex+="(${csi}[?]1006$qregex)?"
    regex+="(${csi}[?]1016$qregex)?"
    regex+="(${csi}4$tregex)?"
    regex+="(${csi}6$tregex)?"
    regex+="(${csi}8$tregex)?"

    [[ $REPLY =~ $regex ]]

    modes=(
        [1000]=${BASH_REMATCH[2]}
        [1002]=${BASH_REMATCH[4]}
        [1006]=${BASH_REMATCH[6]}
        [1016]=${BASH_REMATCH[8]}
    )

        winpx=(${BASH_REMATCH[10]} ${BASH_REMATCH[11]})
       cellpx=(${BASH_REMATCH[13]} ${BASH_REMATCH[14]})
    termcells=(${BASH_REMATCH[16]} ${BASH_REMATCH[17]})

    if (((modes[1016]&1) != 1)); then # mouse will not report pixel events
        winpx[0]=$((termcells[0]*2)) winpx[1]=${termcells[1]}
        cellpx=(1 1)
    elif ((!${#cellpx[@]} && ${#winpx[@]} && ${#termcells[@]})); then
        ((cellpx[0]=winpx[0]/termcells[0], cellpx[1]=winpx[1]/termcells[1]))
    fi

    if ((!${#cellpx[@]})); then
        die "could not get cell size :(   reply=${REPLY@Q}"
    fi

    rows=${termcells[0]}
    cols=${termcells[1]}

    winh=${winpx[0]}
    winw=${winpx[1]}
    rowh=${cellpx[0]}
    colw=${cellpx[1]}
    hrow=$((rowh/2)) # halfrow

    printf '\e[48;2;0;0;0m\e[H'
    printf '%*s' "$((termcells[0]*termcells[1]))"
}
initterm

# do not reinit the whole thing on sigwinch
escapes=(
    '\e[?1016h' # mouse returns pixels
    '\e[14t'    # window size in pixels
    '\e[16t'    # cell size in pixels
    '\e[18t'    # term size in cells
)
trap initterm winch

mouseregex=$'^\e\[<([0-9]+);([-0-9]+);([-0-9]+)([mM])(.*)' # can be negative!!!
getinput () {
    local input
    while read -rn1; do
        input+=$REPLY
        case $input in
            $'\e[<'+([-0-9;])[mM])
                [[ $input =~ $mouseregex ]]
                input=${BASH_REMATCH[-1]}
                BUTTON=("${BASH_REMATCH[@]:1:4}")
                # yes of course we must swap the height and width every time
                # otherwise this api would be too simple to use
                (( BUTTON[1] < 0 || BUTTON[1] >= winw )) && continue
                (( BUTTON[2] < 0 || BUTTON[2] >= winh )) && continue
                return
                ;;
            # csi/ss3 arrows | non csi escape | weird csi
            $'\e'[[O][ABCD]  | $'\e'[^[]      | $'\e['*([0-?])*([ -/])[@-~]) input= ;;
            $'\e'*) ;; # incomplete csi
            *) input= ;; # weird keyboard input?
        esac
    done
}

getmouse () {
    getinput

    ((
      col   = BUTTON[1] / colw + 1,
      row   = BUTTON[2] / rowh + 1,
      hilo  = (BUTTON[2] % rowh) > hrow,
      hirow = row * 2,
      lorow = row * 2 + 1,
      subrow = row * 2 + hilo
    ))
}

fills=(
    ' ' '▄'
    '▀' '█'
)


#      r      |     g     |     b     | rdx | gdx | bdx
# ------------+-----------+-----------+-----+-----+----
# max         | 0->max    | 0         |  0  |  1  |  0
# max->0      |    max    | 0         | -1  |  0  |  0
#      0      |    max    | 0->max    |  0  |  0  |  1
#      0      |    max->0 |    max    |  0  | -1  |  0
#      0->max |         0 |    max    |  1  |  0  |  0
#         max |         0 |    max->0 |  0  |  0  | -1

# walk around an rgb cube on the edges that don't include black or white
# this is equivalent to picking all the colours in hsl with 100% saturation
walkcube () {
    local max=$(($1-1)) fmt=$2
    local rdx=4 gdx=2 bdx=0
    local r=max g=0 b=0
    local i j

    for (( i = 0; i < 6; i++ )) do
        for (( j = 0; j < max; j++ )) do
            printf -v 'hues[i*max+j]' "$fmt" \
                "$(( r += (rdx%6==2)-(rdx%6==5) ))" \
                "$(( g += (gdx%6==2)-(gdx%6==5) ))" \
                "$(( b += (bdx%6==2)-(bdx%6==5) ))"
        done
        (( rdx = (rdx+1) % 6, gdx = (gdx+1) % 6, bdx = (bdx+1) % 6 ))
    done
}

# 256col hues:
# declare -ai hues
# walkcube 6 '16 + %d*6*6 + %d*6 + %d'

# rgb hues:
hues=()
walkcube 256 '%d;%d;%d'

h=${#hues[@]}
hues+=("0;0;0")

declare -A states=()

winmin=$((winpx[0]<winpx[1]?winpx[0]:winpx[1]))

# the standard wyvill 6th degree polynomial:
# f(d) = (1 - (d/R)^2)^3   if d <= R, else 0
# it's C^2 continuous, and it has compact support, so there is no effect after R^2
# we can thus add each ball independently

# to evaluate it in fixed point maths, pick a scale so that we never overflow
scale=$((1<<16))

# for now all our balls will have the same radius
 R=$((scale*winmin/5))
R2=$((scale*winmin**2/25))
S2=$((scale*scale*winmin**2/25))

wyvill='d2<S2?scale-d2/R2:0'
field='wyvill*wyvill/100/scale*wyvill/scale'

times=()

declare -A f

alpha=({A..Z} {a..z} {0..9})
expr=(
    'y=c*colw*scale'
    'd2=(xdhi+(y-cy)**2),hi=(f[' ']+=field),hi=hi>LO&&hi<HI?255:0'
    'd2=(xdlo+(y-cy)**2),lo=(f[' ']+=field),lo=lo>LO&&lo<HI?255:0'
)
drawball() {
    local d2
    local rhi rlo rmin rmax c cmin cmax
    local cx=$1 cy=$2
    local x y
    local hi lo
    local wh=$(((winh-2)*scale)) ww=$(((winw-2)*scale))

    if (((modes[1016]&1) == 1)); then
        ((rmin = (cx-R>=0?cx-R:0 )/scale/rowh*2))
        ((rmax = (cx+R<wh?cx+R:wh)/scale/rowh*2+1))
        ((cmin = (cy-R>=0?cy-R:0 )/scale/colw))
        ((cmax = (cy+R<ww?cy+R:ww)/scale/colw))
        #echo debug:$tid:mode1016=1,rmin=$rmin,rmax=$rmax >&2

        for ((rhi=rmin;rhi<=rmax;rhi+=2)) do
            ((rhi % NTHR == tid )) || continue
            printf '\e[%s;%sH' "$((rhi/2+1))" "$((cmin+1))"
            ((x=rhi/2*rowh*scale,rlo=rhi+hrow*scale))
            ((xdhi=(x-cx)**2,xdlo=(x+hrow*scale-cx)**2))

            for ((c=cmin;c<=cmax;c++)) do
                ((${expr[0]},${expr[1]}$rhi,$c${expr[2]},${expr[3]}$rlo,$c${expr[4]}))
                printf '\e[38;2;%s;%s;%s;48;2;%s;%s;%sm▀' "$hi" "$hi" "$hi" "$lo" "$lo" "$lo"
            done
        done
    else
        ((cx*=2))
        ((rmin = (cx-R>=0?cx-R:0 )/scale/2))
        ((rmax = (cx+R<wh?cx+R:wh)/scale/2))
        ((cmin = (cy-R>=0?cy-R:0 )/scale/2*2))
        ((cmax = (cy+R<ww?cy+R:ww)/scale/2*2))

        for ((r=rmin;r<=rmax;r++)) do
            ((rhi % NTHR == tid )) || continue
            printf '\e[%s;%sH' "$((r+1))" "$((cmin+1))"
            ((x=r*2*scale,xdhi=(x-cx)**2))

            for ((c=cmin;c<=cmax;c+=2)) do
                ((${expr[0]},${expr[1]}$r,$c${expr[2]}))
                printf '\e[48;2;%s;%s;%sm  ' "$hi" "$hi" "$hi"
            done
        done
    fi
}
run_listeners

while getmouse; do
    [[ ${BUTTON[3]} = m ]] || continue
    cy=$((BUTTON[1]*scale))
    cx=$((BUTTON[2]*scale))

    t0=${EPOCHREALTIME/.}
    dispatch 'drawball "$cx" "$cy" > buffered."$tid"; printf x'
    for ((t=0;t<NTHR;t++)) do
        read -rn1 -u"${notify[t]}"
        read -rd '' 'buffered[t]' < buffered."$t"
    done
    printf %s "${buffered[@]}"
    t1=${EPOCHREALTIME/.}
    balltimes+=($((t1-t0)))
done
