#!/bin/bash

shopt -s extglob

diemsg=
die () { diemsg=$*; exit 1; }

resetterm () {
    local escapes=(
        '\e[m'      # sgr state
        '\e[?25h'   # show cursor
        '\e8'       # restore cursor pos
        '\e[?1049l' # alt screen off
        '\e[?1000l' # mouse mode
        '\e[?1006l' # sgr mouse mode idk whatever
        '\e[?1002l' # mouse button even tracking
        '\e[?1016l' # mouse returns pixels
        '\e8'       # restore cursor pos
    )
    printf %b "${escapes[@]}"
    stty sane
}

trap 'resetterm; [[ $diemsg ]] && echo $diemsg' exit
stty -echo

escapes=(
   #'\e[?1049h' # alt screen
   #'\e[J'      # erase screen
    '\e[?25l'   # hide cursor
    '\e7'       # save cursor pos
    '\e[?1000h' # mouse mode
    '\e[?1006h' # sgr mouse mode idk whatever
    '\e[?1002h' # mouse button even tracking
    '\e[?1016h' # mouse returns pixels
    '\e[14t'    # window size in pixels
    '\e[16t'    # cell size in pixels
    '\e[18t'    # term size in cells
    '\e[?6n'    # cursor position just to definitely get a reply
)

initterm () {
    local REPLY
    while read -rn1 -t.01; [[ $REPLY ]]; do :; done

    printf %b "${escapes[@]}"
    read -r -t.1 -d R
    csi=$'\e\['
    tregex=';([^;]+);([^t]+)t'
    regex="^(${csi}4$tregex)?(${csi}6$tregex)?(${csi}8$tregex)?"
    [[ $REPLY =~ $regex ]]

        winpx=(${BASH_REMATCH[2]} ${BASH_REMATCH[3]})
       cellpx=(${BASH_REMATCH[5]} ${BASH_REMATCH[6]})
    termcells=(${BASH_REMATCH[8]} ${BASH_REMATCH[9]})

    if ((!${#cellpx[@]} && ${#winpx[@]} && ${#termcells[@]})); then
        ((cellpx[0]=winpx[0]/termcells[0], cellpx[1]=winpx[1]/termcells[1]))
    fi
    if ((!${#cellpx[@]})); then
        die "could not get cell size :(   reply=${REPLY@Q}"
    fi

    rows=${termcells[0]}
    cols=${termcells[1]}

    rowheight=${cellpx[0]}
    colwidth=${cellpx[1]}
    halfrow=$((rowheight/2))
}
initterm

# do not reinit the whole thing on sigwinch
escapes=(
    '\e[?1016h' # mouse returns pixels
    '\e[14t'    # window size in pixels
    '\e[16t'    # cell size in pixels
    '\e[18t'    # term size in cells
)
trap initterm winch

mouseregex=$'^\e\[<([0-9]+);([-0-9]+);([-0-9]+)([mM])(.*)' # can be negative!!!
getinput () {
    local input
    while read -rn1; do
        input+=$REPLY
        printf '\e[3;1H\e[m\e[Kinput=%s winpx=%s' "${input@Q}" "${winpx[*]@Q}"
        case $input in
            $'\e[<'+([-0-9;])[mM])
                [[ $input =~ $mouseregex ]]
                input=${BASH_REMATCH[-1]}
                BUTTON=("${BASH_REMATCH[@]:1:4}")
                # yes of course we must swap the height and width every time
                # otherwise this api would be too simple to use
                (( BUTTON[1] < 0 || BUTTON[1] >= winpx[1] )) && continue
                (( BUTTON[2] < 0 || BUTTON[2] >= winpx[0] )) && continue
                return
                ;;
            # csi/ss3 arrows | non csi escape | weird csi
            $'\e'[[O][ABCD]  | $'\e'[^[]      | $'\e['*([0-?])*([ -/])[@-~]) input= ;;
            $'\e'*) ;; # incomplete csi
            *) input= ;; # weird keyboard input?
        esac
    done
}

getmouse () {
    getinput

    ((
      col   = BUTTON[1] / colwidth + 1,
      row   = BUTTON[2] / rowheight + 1,
      hilo  = (BUTTON[2] % rowheight) > halfrow,
      hirow = row * 2,
      lorow = row * 2 + 1,
      subrow = row * 2 + hilo
    ))
}

fills=(
    ' ' '▄'
    '▀' '█'
)


#      r      |     g     |     b     | rdx | gdx | bdx
# ------------+-----------+-----------+-----+-----+----
# max         | 0->max    | 0         |  0  |  1  |  0
# max->0      |    max    | 0         | -1  |  0  |  0
#      0      |    max    | 0->max    |  0  |  0  |  1
#      0      |    max->0 |    max    |  0  | -1  |  0
#      0->max |         0 |    max    |  1  |  0  |  0
#         max |         0 |    max->0 |  0  |  0  | -1

# walk around an rgb cube on the edges that don't include black or white
# this is equivalent to picking all the colours in hsl with 100% saturation
walkcube () {
    local max=$(($1-1)) fmt=$2
    local rdx=4 gdx=2 bdx=0
    local r=max g=0 b=0
    local i j

    for (( i = 0; i < 6; i++ )) do
        for (( j = 0; j < max; j++ )) do
            printf -v 'hues[i*max+j]' "$fmt" \
                "$(( r += (rdx%6==2)-(rdx%6==5) ))" \
                "$(( g += (gdx%6==2)-(gdx%6==5) ))" \
                "$(( b += (bdx%6==2)-(bdx%6==5) ))"
        done
        (( rdx = (rdx+1) % 6, gdx = (gdx+1) % 6, bdx = (bdx+1) % 6 ))
    done
}

# 256col hues:
# declare -ai hues
# walkcube 6 '16 + %d*6*6 + %d*6 + %d'

# rgb hues:
hues=()
walkcube 256 '%d;%d;%d'

h=${#hues[@]}
hues+=("0;0;0")

declare -A states=()
while getmouse; do
    (( states[$subrow,$col]=q++%h ))
    (( fill = states[$hirow,$col] * 2 + states[$lorow,$col] ))
    printf '\e[%s;%sH\e[38;2;%s;48;2;%sm▀' "$row" "$col" "${hues[${states[$hirow,$col]-h}]}" "${hues[${states[$lorow,$col]-h}]}"
done
